### ISSUE TITLE
How to set this up ?

### ISSUE THREAD

**Issue by SimonMellerin** [ashthespy/SpotConnect#1]
Hi,

I would like to use your daemon, can you explain me how to set it up on my Volumio instance ?

Thanks !
Simon

**Comment by ashthespy** [comment]
Heya! 
The hard way would be to compile this source, 
and then incorporate the plugin's `index.js` from [this PR](https://github.com/balbuze/volumio-plugins/pull/89)
However, @balbuze has incorporated all these changes and packaged it in a ready to install [plugin](https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect)

Cheers!

**Comment by SimonMellerin** [comment]
Nice ! thanks

**Comment by SimonMellerin** [comment]
Nice !

Thanks
